"""Initial migration

Revision ID: 7c4793fbdf83
Revises: 
Create Date: 2026-01-11 10:09:53.147465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4793fbdf83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet_plan')
    op.drop_table('details')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=12000),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=20000),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)

    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=3000),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('option_d',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('recorded_class', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=3000),
               existing_nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('studymaterial', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=3000),
               existing_nullable=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('qualifications',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('contact',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('place',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('place',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('contact',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('availability',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('qualifications',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('studymaterial', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('student_answer', schema=None) as batch_op:
        batch_op.alter_column('selected_option',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('recorded_class', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.alter_column('option_d',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('option_c',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('option_b',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('live_class', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=20000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=12000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    op.create_table('details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('activity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bmi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('details_pkey'))
    )
    op.create_table('diet_plan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('diet_plan_pkey'))
    )
    # ### end Alembic commands ###
