"""initial

Revision ID: 8d8ab681eb17
Revises: 
Create Date: 2026-01-10 15:49:21.388197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8ab681eb17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('qualifications', sa.String(length=200), nullable=False),
    sa.Column('availability', sa.String(length=100), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=15), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_attendance_student'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='fk_attendance_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_exam_course'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='fk_exam_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_live_course'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='fk_live_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recorded_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_recorded_course'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='fk_recorded_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_student_course_course'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_student_course_student'),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_table('studymaterial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_material_course'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='fk_material_teacher'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_course',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_teacher_course_course'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='fk_teacher_course_teacher'),
    sa.PrimaryKeyConstraint('teacher_id', 'course_id')
    )
    op.create_table('exam_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attended_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name='fk_result_exam'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_result_student'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('recorded_class_id', sa.Integer(), nullable=True),
    sa.Column('live_class_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_progress_course'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name='fk_progress_exam'),
    sa.ForeignKeyConstraint(['live_class_id'], ['live_class.id'], name='fk_progress_live'),
    sa.ForeignKeyConstraint(['material_id'], ['studymaterial.id'], name='fk_progress_material'),
    sa.ForeignKeyConstraint(['recorded_class_id'], ['recorded_class.id'], name='fk_progress_recorded'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_progress_student'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=200), nullable=False),
    sa.Column('option_b', sa.String(length=200), nullable=False),
    sa.Column('option_c', sa.String(length=200), nullable=True),
    sa.Column('option_d', sa.String(length=200), nullable=True),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name='fk_question_exam'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name='fk_answer_exam'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_answer_question'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_answer_student'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_answer')
    op.drop_table('question')
    op.drop_table('progress')
    op.drop_table('exam_result')
    op.drop_table('exam_attempt')
    op.drop_table('teacher_course')
    op.drop_table('studymaterial')
    op.drop_table('student_course')
    op.drop_table('recorded_class')
    op.drop_table('live_class')
    op.drop_table('exam')
    op.drop_table('attendance')
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_table('feedback')
    op.drop_table('course')
    op.drop_table('admin')
    # ### end Alembic commands ###
